### ISSUE TITLE
[BUG] Conversion is broken.

### ISSUE THREAD

**Issue by chdominguez** [J-Fabila/VASP_to_XYZ#2]
The program does not correctly convert either POSCAR nor CONTCAR files. For the sample POSCAR file, every line turns to 0 or 1. For the CONTCAR, the first part is correct but after the Silicon atoms the program starts writing 0 everywhere.

I attach the inputs and the outputs as examples.

[ConvertedFiles.zip](https://github.com/J-Fabila/VASP_to_XYZ/files/9639683/ConvertedFiles.zip)

**Comment by J-Fabila** [comment]
Hello, the program  works for the format  described here:  https://www.vasp.at/wiki/index.php/POSCAR
for example:

Cubic BN 
3.57
0.0 0.5 0.5
0.5 0.0 0.5
0.5 0.5 0.0
B N
1 1
Direct
0.00 0.00 0.00 
0.25 0.25 0.25

The atomic symbols are written in the 5th line, so with  your POSCAR file the program is not finding any, but if you switch the line to the 5th it will work.

Regarding the CONTCAR file the problem is that  the program is  not implemented to skip ionic velocities, thus you have to remove those last lines and it will work.
I attach the inputs with those modifications


[archivos.zip](https://github.com/J-Fabila/VASP_to_XYZ/files/9647778/archivos.zip)
[archivos.zip](https://github.com/J-Fabila/VASP_to_XYZ/files/9647785/archivos.zip)
